<?php

declare(strict_types=1);

function default_settings(): array
{
    return [
        'brand_name' => 'نگاه مدیا',
        'brand_descriptor' => 'استودیو خلاقیت و رشد',
        'hero_kicker' => 'استودیوی خلاقیت و رشد دیجیتال',
        'hero_title' => 'برند شما،',
        'hero_highlight' => 'از زاویه‌ای تازه.',
        'hero_description' => 'برای برندهایی که می‌خواهند متفاوت دیده شوند؛ از ایده و هویت بصری تا کمپین‌های دیجیتالِ نتیجه‌محور، کنار شما هستیم.',
        'hero_primary_label' => 'برای شروع گفت‌وگو',
        'hero_primary_url' => '#contact',
        'hero_secondary_label' => 'دیدن روایت پروژه‌ها',
        'hero_secondary_url' => '#portfolio',
        'hero_image' => 'assets/img/hero-persian-campaign.webp',
        'hero_proof_first' => 'از شناخت دقیق تا',
        'hero_proof_second' => 'اثر ماندگار، همراه برندها هستیم.',
        'stat_projects' => '۴',
        'stat_projects_label' => 'مسیر تخصصی',
        'stat_years' => '۳',
        'stat_years_label' => 'گام تا اجرای ایده',
        'stat_growth' => '۱',
        'stat_growth_label' => 'تیم در کنار شما',
        'stat_note' => 'فکر خوب، با اثر خوب کامل می‌شود.',
        'services_footnote' => 'از یک قدم کوچک تا یک تحول بزرگ، مسیر را با هم طراحی می‌کنیم.',
        'services_footnote_link' => 'ببینیم چطور؟',
        'portfolio_note' => 'نمونه‌های این صفحه مفهومی هستند و برای نمایش اولیه ساخته شده‌اند.',
        'portfolio_cta' => 'پروژه بعدی را با هم بسازیم',
        'about_button_label' => 'بیشتر با هم آشنا شویم',
        'testimonials_intro' => 'بهترین نشانِ کار خوب، حرف کسانی‌ست که در این مسیر کنارمان بوده‌اند.',
        'testimonials_disclaimer' => 'نام‌ها و روایت‌های صفحه، نمونه هستند و پیش از انتشار نهایی باید با اطلاعات واقعی جایگزین شوند.',
        'journal_description' => 'یادداشت‌های کوتاه ما درباره برند، تبلیغات و تجربه‌های دیجیتال.',
        'contact_form_title' => 'از اینجا شروع کنیم',
        'contact_form_subtitle' => 'پاسخ‌گویی در اولین فرصت',
        'contact_form_name_label' => 'نام و نام خانوادگی',
        'contact_form_name_placeholder' => 'مثلاً نازنین محمدی',
        'contact_form_phone_label' => 'شماره تماس',
        'contact_form_phone_placeholder' => '۰۹۱۲ ۳۴۵ ۶۷۸۹',
        'contact_form_email_label' => 'ایمیل',
        'contact_form_email_placeholder' => 'name@example.com',
        'contact_form_subject_label' => 'موضوع همکاری',
        'contact_form_subjects' => "هویت و برندینگ\nکمپین تبلیغاتی\nبازاریابی دیجیتال\nمشاوره و استراتژی\nسایر",
        'contact_form_message_label' => 'کمی از پروژه برایمان بگویید',
        'contact_form_message_placeholder' => 'چه مسئله‌ای را می‌خواهید با هم حل کنیم؟',
        'contact_form_submit' => 'ارسال درخواست',
        'contact_privacy_note' => 'اطلاعات شما فقط برای پیگیری همین درخواست استفاده می‌شود.',
        'footer_quick_links_title' => 'دسترسی سریع',
        'footer_brand_links_title' => 'با نگاه مدیا',
        'footer_contact_title' => 'راه‌های ارتباطی',
        'services_eyebrow' => 'توانمندی‌های ما',
        'services_title' => "از ایده تا اثری که\nدر ذهن می‌ماند",
        'services_description' => 'هر نقطه تماس برند شما، فرصتی‌ست برای ساختن یک تجربه بهتر. ما این فرصت‌ها را با نگاه استراتژیک و اجرای خلاق به هم وصل می‌کنیم.',
        'portfolio_eyebrow' => 'قصه‌هایی که ساخته‌ایم',
        'portfolio_title' => 'چند قاب از نگاه ما',
        'portfolio_description' => 'هر همکاری، یک مسئله تازه و یک فرصت برای ساختن چیزی ماندگار است.',
        'about_eyebrow' => 'نگاه ما به ماجرا',
        'about_title' => "خلاقیت، وقتی\nاثرگذار است که\nجهت داشته باشد.",
        'about_description' => 'ما یک تیم مستقل از استراتژیست‌ها، طراحان و سازندگانیم؛ با یک باور مشترک: تبلیغات خوب فقط دیده نمی‌شود، چیزی را در رفتار و ذهن مخاطب تغییر می‌دهد.',
        'about_quote' => '«ما به جای صدای بلندتر، دنبال پیام دقیق‌تریم.»',
        'about_metric' => '۱ نگاه، بی‌نهایت امکان',
        'about_metric_label' => 'ترکیب درستِ داده، خلاقیت و اجرا',
        'process_eyebrow' => 'مسیر همکاری',
        'process_title' => "قدم‌به‌قدم،\nرو به جلو",
        'process_description' => 'مسیر روشن، همکاری را ساده‌تر می‌کند. از شنیدن مسئله تا سنجش نتیجه، کنار شما می‌مانیم.',
        'testimonials_eyebrow' => 'از زبان همراهان',
        'testimonials_title' => 'اعتماد، در جزئیات ساخته می‌شود',
        'journal_eyebrow' => 'دفترچه نگاه',
        'journal_title' => 'فکرهایی برای فردا',
        'nav_services' => 'خدمات',
        'nav_portfolio' => 'نمونه‌کارها',
        'nav_about' => 'درباره ما',
        'nav_journal' => 'دفترچه نگاه',
        'nav_contact' => 'ارتباط با ما',
        'process_step_1_title' => 'شنیدن و شناخت',
        'process_step_1_text' => 'اهداف، مخاطب و چالش اصلی کسب‌وکار را با دقت می‌شناسیم.',
        'process_step_2_title' => 'چیدن نقشه',
        'process_step_2_text' => 'بینش‌ها را به استراتژی، پیام و برنامه‌ای قابل اجرا تبدیل می‌کنیم.',
        'process_step_3_title' => 'ساختن و اجرا',
        'process_step_3_text' => 'با تیم‌های تخصصی، ایده را در تمام نقاط تماس زنده می‌کنیم.',
        'process_step_4_title' => 'سنجش و رشد',
        'process_step_4_text' => 'نتیجه‌ها را می‌سنجیم، یاد می‌گیریم و مسیر را بهتر می‌کنیم.',
        'contact_eyebrow' => 'یک شروع تازه',
        'contact_title' => "از ایده‌تان\nبرایمان بگویید.",
        'contact_description' => 'فرم کوتاه روبه‌رو را پر کنید؛ در اولین فرصت برای یک گفت‌وگوی بی‌تکلف با شما تماس می‌گیریم.',
        'contact_phone' => '۰۲۱ ـ ۸۸۴۴ ۷۳۱۰',
        'contact_email' => 'hello@negaah.media',
        'contact_address' => 'تهران، خیابان ولیعصر، استودیو نگاه',
        'social_instagram' => 'https://instagram.com/',
        'social_linkedin' => 'https://linkedin.com/',
        'social_telegram' => 'https://t.me/',
        'footer_description' => 'به برندها کمک می‌کنیم روشن‌تر ببینند، هوشمندانه‌تر روایت کنند و ماندگارتر رشد کنند.',
        'theme_primary' => '#155C5A',
        'theme_accent' => '#BD5D43',
        'theme_saffron' => '#D7A84A',
        'theme_ink' => '#1E2C2B',
        'theme_surface' => '#F6F3EA',
    ];
}

function default_services(): array
{
    return [
        ['id' => 1, 'name' => 'استراتژی و مشاوره', 'slug' => 'strategy', 'tagline' => 'اول، درست ببینیم.', 'description' => 'شناخت بازار و مخاطب، جایگاه‌یابی برند و طراحی نقشه‌ای شفاف برای رشد.', 'icon' => 'compass', 'sort_order' => 1, 'is_published' => 1],
        ['id' => 2, 'name' => 'هویت و طراحی برند', 'slug' => 'branding', 'tagline' => 'شبیه خودتان باشید.', 'description' => 'از نام و نشان تا لحن کلام؛ هویتی منسجم که به یاد می‌ماند و اعتماد می‌سازد.', 'icon' => 'spark', 'sort_order' => 2, 'is_published' => 1],
        ['id' => 3, 'name' => 'کمپین و تولید محتوا', 'slug' => 'campaigns', 'tagline' => 'حرفی برای گفتن.', 'description' => 'ایده‌های کمپین، تولید محتوای چندرسانه‌ای و روایت‌هایی که مخاطب را درگیر می‌کنند.', 'icon' => 'megaphone', 'sort_order' => 3, 'is_published' => 1],
        ['id' => 4, 'name' => 'بازاریابی دیجیتال', 'slug' => 'digital', 'tagline' => 'رشد، با عدد و معنا.', 'description' => 'از طراحی تجربه دیجیتال و سئو تا بهینه‌سازی تبلیغات بر پایه داده و نتیجه.', 'icon' => 'chart', 'sort_order' => 4, 'is_published' => 1],
    ];
}

function default_projects(): array
{
    return [
        ['id' => 1, 'title' => 'ریشه؛ روایت یک طعم اصیل', 'client' => 'برند ریشه', 'category' => 'هویت بصری', 'excerpt' => 'بازآفرینی هویت یک برند محصولات بومی با الهام از نقش‌مایه‌های ایرانی.', 'description' => '', 'image' => '', 'visual_theme' => 'saffron', 'metrics' => 'پروژه مفهومی', 'sort_order' => 1, 'is_published' => 1],
        ['id' => 2, 'title' => 'نقش؛ خانه‌ای برای فرم‌های تازه', 'client' => 'استودیو نقش', 'category' => 'دیجیتال و تجربه کاربری', 'excerpt' => 'طراحی تجربه خرید آنلاین با تمرکز بر سادگی و کشف محصول.', 'description' => '', 'image' => '', 'visual_theme' => 'teal', 'metrics' => 'پروژه مفهومی', 'sort_order' => 2, 'is_published' => 1],
        ['id' => 3, 'title' => 'دُرنا؛ انرژی یک شروع نو', 'client' => 'دُرنا', 'category' => 'کمپین تبلیغاتی', 'excerpt' => 'کمپینی یکپارچه برای معرفی محصولی تازه به نسلی تازه.', 'description' => '', 'image' => '', 'visual_theme' => 'coral', 'metrics' => 'پروژه مفهومی', 'sort_order' => 3, 'is_published' => 1],
    ];
}

function default_testimonials(): array
{
    return [
        ['id' => 1, 'name' => 'سارا امینی', 'role' => 'مدیر برند', 'company' => 'همراه پروژه ریشه', 'quote' => 'نگاه مدیا خیلی زود مسئله اصلی برند را فهمید. خروجی فقط زیبا نبود؛ تیم ما بالاخره زبان مشترکی برای معرفی محصول پیدا کرد.', 'sort_order' => 1, 'is_published' => 1],
        ['id' => 2, 'name' => 'آرمان نیک‌پی', 'role' => 'بنیان‌گذار', 'company' => 'همراه پروژه نقش', 'quote' => 'از روز اول تا اجرا، حس کردیم یک تیم هم‌مسیر کنارمان است؛ دقیق، خوش‌فکر و متعهد به نتیجه.', 'sort_order' => 2, 'is_published' => 1],
        ['id' => 3, 'name' => 'مهتاب یوسفی', 'role' => 'مدیر بازاریابی', 'company' => 'همراه پروژه دُرنا', 'quote' => 'کمپین با یک ایده ساده شروع شد و با برنامه‌ریزی دقیق به گفت‌وگویی واقعی با مخاطبان ما تبدیل شد.', 'sort_order' => 3, 'is_published' => 1],
    ];
}

function default_articles(): array
{
    return [
        ['id' => 1, 'title' => 'چطور یک برند، صدای خودش را پیدا می‌کند؟', 'slug' => 'finding-brand-voice', 'category' => 'برندینگ', 'excerpt' => 'لحن برند، فقط چند واژه در شبکه‌های اجتماعی نیست؛ تجربه‌ای‌ست که در تمام تماس‌ها شکل می‌گیرد.', 'body' => "لحن برند فقط چند واژه در شبکه‌های اجتماعی نیست؛ تجربه‌ای‌ست که در تمام تماس‌ها شکل می‌گیرد. از نخستین آگهی تا پاسخ پشتیبانی، صدای برند باید یک‌پارچه، صادقانه و متناسب با آدم‌هایی باشد که با آن حرف می‌زند.\n\nبرای پیدا کردن این صدا، از ارزش‌ها شروع کنید، مخاطب را خوب بشناسید و چند اصل ساده برای نوشتن و گفت‌وگو تعریف کنید. بعد، همان اصول را در تمام کانال‌ها تمرین و بازبینی کنید.", 'image' => '', 'published_at' => date('Y-m-d'), 'is_published' => 1],
        ['id' => 2, 'title' => 'کمپین خوب از پرسیدن سؤال درست شروع می‌شود', 'slug' => 'better-campaigns', 'category' => 'استراتژی', 'excerpt' => 'پیش از انتخاب رسانه و فرمت، باید بدانیم قرار است چه چیزی در مخاطب تغییر کند.', 'body' => "پیش از انتخاب رسانه و فرمت، باید بدانیم قرار است چه چیزی در مخاطب تغییر کند. کمپین زمانی جهت پیدا می‌کند که یک مسئله روشن، یک مخاطب مشخص و یک هدف قابل سنجش داشته باشد.\n\nبا پرسیدن سؤال درست، ایده از حد یک تصویر جذاب فراتر می‌رود و به تجربه‌ای تبدیل می‌شود که مخاطب آن را می‌فهمد، به یاد می‌آورد و درباره‌اش حرف می‌زند.", 'image' => '', 'published_at' => date('Y-m-d'), 'is_published' => 1],
    ];
}

function content_groups(): array
{
    return [
        'مشخصات برند و ارتباط' => [
            ['key' => 'brand_name', 'label' => 'نام برند', 'type' => 'text'],
            ['key' => 'brand_descriptor', 'label' => 'توضیح کوتاه برند', 'type' => 'text'],
            ['key' => 'nav_services', 'label' => 'عنوان پیوند خدمات', 'type' => 'text'],
            ['key' => 'nav_portfolio', 'label' => 'عنوان پیوند نمونه‌کارها', 'type' => 'text'],
            ['key' => 'nav_about', 'label' => 'عنوان پیوند درباره ما', 'type' => 'text'],
            ['key' => 'nav_journal', 'label' => 'عنوان پیوند دفترچه نگاه', 'type' => 'text'],
            ['key' => 'nav_contact', 'label' => 'عنوان پیوند تماس', 'type' => 'text'],
            ['key' => 'footer_quick_links_title', 'label' => 'عنوان ستون پیوندهای سریع', 'type' => 'text'],
            ['key' => 'footer_brand_links_title', 'label' => 'عنوان ستون همکاری', 'type' => 'text'],
            ['key' => 'footer_contact_title', 'label' => 'عنوان ستون راه‌های ارتباطی', 'type' => 'text'],
            ['key' => 'footer_description', 'label' => 'معرفی کوتاه در پایین سایت', 'type' => 'textarea'],
            ['key' => 'contact_phone', 'label' => 'شماره تماس', 'type' => 'text'],
            ['key' => 'contact_email', 'label' => 'ایمیل', 'type' => 'text'],
            ['key' => 'contact_address', 'label' => 'نشانی', 'type' => 'text'],
            ['key' => 'social_instagram', 'label' => 'پیوند اینستاگرام', 'type' => 'text'],
            ['key' => 'social_linkedin', 'label' => 'پیوند لینکدین', 'type' => 'text'],
            ['key' => 'social_telegram', 'label' => 'پیوند تلگرام', 'type' => 'text'],
        ],
        'بخش آغازین' => [
            ['key' => 'hero_kicker', 'label' => 'برچسب بالای تیتر', 'type' => 'text'],
            ['key' => 'hero_title', 'label' => 'تیتر اصلی ـ بخش اول', 'type' => 'text'],
            ['key' => 'hero_highlight', 'label' => 'تیتر اصلی ـ بخش رنگی', 'type' => 'text'],
            ['key' => 'hero_description', 'label' => 'توضیح آغازین', 'type' => 'textarea'],
            ['key' => 'hero_primary_label', 'label' => 'متن دکمه اصلی', 'type' => 'text'],
            ['key' => 'hero_primary_url', 'label' => 'پیوند دکمه اصلی', 'type' => 'text'],
            ['key' => 'hero_secondary_label', 'label' => 'متن دکمه دوم', 'type' => 'text'],
            ['key' => 'hero_secondary_url', 'label' => 'پیوند دکمه دوم', 'type' => 'text'],
            ['key' => 'hero_image', 'label' => 'مسیر تصویر آغازین', 'type' => 'text'],
            ['key' => 'hero_proof_first', 'label' => 'جملهٔ همراه بخش آغازین ـ خط اول', 'type' => 'text'],
            ['key' => 'hero_proof_second', 'label' => 'جملهٔ همراه بخش آغازین ـ خط دوم', 'type' => 'text'],
            ['key' => 'stat_projects', 'label' => 'آمار اول', 'type' => 'text'],
            ['key' => 'stat_projects_label', 'label' => 'توضیح آمار اول', 'type' => 'text'],
            ['key' => 'stat_years', 'label' => 'آمار دوم', 'type' => 'text'],
            ['key' => 'stat_years_label', 'label' => 'توضیح آمار دوم', 'type' => 'text'],
            ['key' => 'stat_growth', 'label' => 'آمار سوم', 'type' => 'text'],
            ['key' => 'stat_growth_label', 'label' => 'توضیح آمار سوم', 'type' => 'text'],
            ['key' => 'stat_note', 'label' => 'یادداشت کنار آمارها', 'type' => 'text'],
        ],
        'بخش خدمات' => [
            ['key' => 'services_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'services_title', 'label' => 'عنوان بخش', 'type' => 'textarea'],
            ['key' => 'services_description', 'label' => 'توضیح بخش', 'type' => 'textarea'],
            ['key' => 'services_footnote', 'label' => 'یادداشت زیر خدمات', 'type' => 'text'],
            ['key' => 'services_footnote_link', 'label' => 'متن پیوند انتهای بخش', 'type' => 'text'],
        ],
        'بخش نمونه‌کارها' => [
            ['key' => 'portfolio_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'portfolio_title', 'label' => 'عنوان بخش', 'type' => 'text'],
            ['key' => 'portfolio_description', 'label' => 'توضیح بخش', 'type' => 'textarea'],
            ['key' => 'portfolio_note', 'label' => 'یادداشت پایین نمونه‌کارها', 'type' => 'text'],
            ['key' => 'portfolio_cta', 'label' => 'متن پیوند پایانی', 'type' => 'text'],
        ],
        'درباره نگاه' => [
            ['key' => 'about_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'about_title', 'label' => 'عنوان بخش', 'type' => 'textarea'],
            ['key' => 'about_description', 'label' => 'متن معرفی', 'type' => 'textarea'],
            ['key' => 'about_quote', 'label' => 'جمله برجسته', 'type' => 'text'],
            ['key' => 'about_metric', 'label' => 'عبارت برجسته', 'type' => 'text'],
            ['key' => 'about_metric_label', 'label' => 'توضیح عبارت برجسته', 'type' => 'text'],
            ['key' => 'about_button_label', 'label' => 'متن دکمه', 'type' => 'text'],
        ],
        'مراحل همکاری' => [
            ['key' => 'process_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'process_title', 'label' => 'عنوان بخش', 'type' => 'textarea'],
            ['key' => 'process_description', 'label' => 'توضیح بخش', 'type' => 'textarea'],
            ['key' => 'process_step_1_title', 'label' => 'گام اول', 'type' => 'text'],
            ['key' => 'process_step_1_text', 'label' => 'توضیح گام اول', 'type' => 'textarea'],
            ['key' => 'process_step_2_title', 'label' => 'گام دوم', 'type' => 'text'],
            ['key' => 'process_step_2_text', 'label' => 'توضیح گام دوم', 'type' => 'textarea'],
            ['key' => 'process_step_3_title', 'label' => 'گام سوم', 'type' => 'text'],
            ['key' => 'process_step_3_text', 'label' => 'توضیح گام سوم', 'type' => 'textarea'],
            ['key' => 'process_step_4_title', 'label' => 'گام چهارم', 'type' => 'text'],
            ['key' => 'process_step_4_text', 'label' => 'توضیح گام چهارم', 'type' => 'textarea'],
        ],
        'دیدگاه همراهان' => [
            ['key' => 'testimonials_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'testimonials_title', 'label' => 'عنوان بخش', 'type' => 'text'],
            ['key' => 'testimonials_intro', 'label' => 'متن معرفی بخش', 'type' => 'textarea'],
            ['key' => 'testimonials_disclaimer', 'label' => 'یادداشت پایین دیدگاه‌ها', 'type' => 'text'],
        ],
        'دفترچه نگاه' => [
            ['key' => 'journal_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'journal_title', 'label' => 'عنوان بخش', 'type' => 'text'],
            ['key' => 'journal_description', 'label' => 'توضیح بخش', 'type' => 'textarea'],
        ],
        'تماس و همکاری' => [
            ['key' => 'contact_eyebrow', 'label' => 'برچسب بخش', 'type' => 'text'],
            ['key' => 'contact_title', 'label' => 'عنوان بخش', 'type' => 'textarea'],
            ['key' => 'contact_description', 'label' => 'توضیح بخش', 'type' => 'textarea'],
            ['key' => 'contact_form_title', 'label' => 'عنوان فرم تماس', 'type' => 'text'],
            ['key' => 'contact_form_subtitle', 'label' => 'توضیح کوتاه فرم', 'type' => 'text'],
            ['key' => 'contact_form_name_label', 'label' => 'عنوان فیلد نام', 'type' => 'text'],
            ['key' => 'contact_form_name_placeholder', 'label' => 'راهنمای فیلد نام', 'type' => 'text'],
            ['key' => 'contact_form_phone_label', 'label' => 'عنوان فیلد تلفن', 'type' => 'text'],
            ['key' => 'contact_form_phone_placeholder', 'label' => 'راهنمای فیلد تلفن', 'type' => 'text'],
            ['key' => 'contact_form_email_label', 'label' => 'عنوان فیلد ایمیل', 'type' => 'text'],
            ['key' => 'contact_form_email_placeholder', 'label' => 'راهنمای فیلد ایمیل', 'type' => 'text'],
            ['key' => 'contact_form_subject_label', 'label' => 'عنوان فیلد موضوع', 'type' => 'text'],
            ['key' => 'contact_form_subjects', 'label' => 'گزینه‌های موضوع فرم (هر گزینه در یک خط)', 'type' => 'textarea'],
            ['key' => 'contact_form_message_label', 'label' => 'عنوان فیلد پیام', 'type' => 'text'],
            ['key' => 'contact_form_message_placeholder', 'label' => 'راهنمای فیلد پیام', 'type' => 'text'],
            ['key' => 'contact_form_submit', 'label' => 'متن دکمهٔ ارسال', 'type' => 'text'],
            ['key' => 'contact_privacy_note', 'label' => 'یادداشت حریم خصوصی', 'type' => 'text'],
        ],
        'رنگ‌بندی سایت' => [
            ['key' => 'theme_primary', 'label' => 'فیروزه‌ای ایرانی ـ رنگ اصلی', 'type' => 'color'],
            ['key' => 'theme_accent', 'label' => 'آجری ـ رنگ مکمل', 'type' => 'color'],
            ['key' => 'theme_saffron', 'label' => 'زعفرانی ـ رنگ تأکیدی', 'type' => 'color'],
            ['key' => 'theme_ink', 'label' => 'جوهر ـ رنگ متن', 'type' => 'color'],
            ['key' => 'theme_surface', 'label' => 'کاغذ ـ رنگ زمینه', 'type' => 'color'],
        ],
    ];
}
